apiVersion: apps/v1
kind: Deployment
metadata:
  name: astra-deployment
  labels:
    app: astra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astra
  template:
    metadata:
      labels:
        app: astra
    spec:
      containers:
      - name: astra
        image: alwindoss/astra:0.0.1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: astra-service
spec:
  type: NodePort
  selector:
    app: astra
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      protocol: TCP
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
